-- Preguntas para la categoría B (Transporte Público)
INSERT INTO preguntas (categoria_id, enunciado, tipo_pregunta, puntaje, dificultad, es_critica) VALUES
(2, '¿Cuál es la velocidad máxima permitida para vehículos de transporte público en zonas urbanas?', 'opcion_multiple', 1.00, 'facil', 1),
(2, '¿Qué documento debe portar obligatoriamente el conductor de un vehículo de transporte público?', 'opcion_multiple', 1.00, 'facil', 1),
(2, '¿Cuál es el tiempo máximo de conducción continuada permitido para conductores de transporte público?', 'opcion_multiple', 1.00, 'facil', 1),
(2, '¿Qué debe hacer el conductor de un vehículo de transporte público cuando se acerca a un paso peatonal?', 'opcion_multiple', 1.00, 'facil', 1),
(2, '¿Cuál es la distancia mínima que debe mantener un vehículo de transporte público respecto a otro vehículo?', 'opcion_multiple', 1.00, 'facil', 1),
(2, '¿Qué luces debe llevar encendidas un vehículo de transporte público durante el día?', 'opcion_multiple', 1.00, 'facil', 1),
(2, '¿Cuál es el procedimiento correcto para el ascenso y descenso de pasajeros?', 'opcion_multiple', 1.00, 'facil', 1),
(2, '¿Qué debe hacer el conductor si un pasajero se siente mal durante el viaje?', 'opcion_multiple', 1.00, 'facil', 1),
(2, '¿Cuál es la documentación que debe exhibir el vehículo de transporte público?', 'opcion_multiple', 1.00, 'facil', 1),
(2, '¿Qué medidas de seguridad debe tener un vehículo de transporte público?', 'opcion_multiple', 1.00, 'facil', 1),
(2, '¿Cuál es el procedimiento en caso de accidente con un vehículo de transporte público?', 'opcion_multiple', 1.00, 'medio', 1),
(2, '¿Qué elementos de seguridad debe revisar el conductor antes de iniciar el servicio?', 'opcion_multiple', 1.00, 'medio', 1),
(2, '¿Cómo debe proceder el conductor en caso de emergencia médica de un pasajero?', 'opcion_multiple', 1.00, 'medio', 1),
(2, '¿Cuál es el protocolo de evacuación en caso de emergencia?', 'opcion_multiple', 1.00, 'medio', 1),
(2, '¿Qué medidas debe tomar el conductor en caso de mal tiempo?', 'opcion_multiple', 1.00, 'medio', 1),
(2, '¿Cómo debe manejar el conductor situaciones de conflicto con pasajeros?', 'opcion_multiple', 1.00, 'medio', 1),
(2, '¿Cuál es el procedimiento para el manejo de equipaje en el vehículo?', 'opcion_multiple', 1.00, 'medio', 1),
(2, '¿Qué debe hacer el conductor si detecta un problema mecánico durante el servicio?', 'opcion_multiple', 1.00, 'medio', 1),
(2, '¿Cómo debe proceder el conductor en caso de robo o asalto?', 'opcion_multiple', 1.00, 'medio', 1),
(2, '¿Cuál es el protocolo de comunicación en caso de emergencia?', 'opcion_multiple', 1.00, 'medio', 1),
(2, '¿Qué medidas debe tomar el conductor para prevenir accidentes?', 'opcion_multiple', 1.00, 'dificil', 0),
(2, '¿Cómo debe manejar el conductor situaciones de tráfico denso?', 'opcion_multiple', 1.00, 'dificil', 0),
(2, '¿Cuál es el procedimiento para el manejo de pasajeros con necesidades especiales?', 'opcion_multiple', 1.00, 'dificil', 0),
(2, '¿Qué debe hacer el conductor en caso de avería en ruta?', 'opcion_multiple', 1.00, 'dificil', 0),
(2, '¿Cómo debe proceder el conductor en caso de desvío de ruta?', 'opcion_multiple', 1.00, 'dificil', 0),
(2, '¿Cuál es el protocolo de seguridad para el manejo de dinero?', 'opcion_multiple', 1.00, 'dificil', 0),
(2, '¿Qué medidas debe tomar el conductor para prevenir el fraude?', 'opcion_multiple', 1.00, 'dificil', 0),
(2, '¿Cómo debe manejar el conductor situaciones de sobrecarga?', 'opcion_multiple', 1.00, 'dificil', 0),
(2, '¿Cuál es el procedimiento para el manejo de quejas de pasajeros?', 'opcion_multiple', 1.00, 'dificil', 0),
(2, '¿Qué debe hacer el conductor en caso de retraso en el servicio?', 'opcion_multiple', 1.00, 'dificil', 0),
(2, '¿Cómo debe proceder el conductor en caso de cierre de vías?', 'opcion_multiple', 1.00, 'dificil', 0),
(2, '¿Cuál es el protocolo de seguridad para el manejo de equipaje especial?', 'opcion_multiple', 1.00, 'dificil', 0),
(2, '¿Qué medidas debe tomar el conductor para prevenir el vandalismo?', 'opcion_multiple', 1.00, 'dificil', 0),
(2, '¿Cómo debe manejar el conductor situaciones de emergencia sanitaria?', 'opcion_multiple', 1.00, 'dificil', 0),
(2, '¿Cuál es el procedimiento para el manejo de pasajeros menores de edad?', 'opcion_multiple', 1.00, 'dificil', 0),
(2, '¿Qué debe hacer el conductor en caso de altercado entre pasajeros?', 'opcion_multiple', 1.00, 'dificil', 0),
(2, '¿Cómo debe proceder el conductor en caso de condiciones climáticas extremas?', 'opcion_multiple', 1.00, 'dificil', 0),
(2, '¿Cuál es el protocolo de seguridad para el manejo de documentos oficiales?', 'opcion_multiple', 1.00, 'dificil', 0),
(2, '¿Qué medidas debe tomar el conductor para prevenir el acoso sexual?', 'opcion_multiple', 1.00, 'dificil', 0),
(2, '¿Cómo debe manejar el conductor situaciones de discriminación?', 'opcion_multiple', 1.00, 'dificil', 0); 